### ISSUE TITLE
File "/home/mona/venv/softras/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1561, in _get_cuda_arch_flags     arch_list[-1] += '+PTX' IndexError: list index out of range

### ISSUE THREAD

**Issue by monacv** [ShichenLiu/SoftRas#72]
Could you please guide me how to fix this error?

```
mona@goku:~/research/code/SoftRas$ source ~/venv/softras/bin/activate
(softras) mona@goku:~/research/code/SoftRas$ python setup.py install
No CUDA runtime is found, using CUDA_HOME='/usr'
running install
running bdist_egg
running egg_info
writing soft_renderer.egg-info/PKG-INFO
writing dependency_links to soft_renderer.egg-info/dependency_links.txt
writing requirements to soft_renderer.egg-info/requires.txt
writing top-level names to soft_renderer.egg-info/top_level.txt
/home/mona/venv/softras/lib/python3.8/site-packages/torch/utils/cpp_extension.py:369: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'soft_renderer.egg-info/SOURCES.txt'
writing manifest file 'soft_renderer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'soft_renderer.cuda.load_textures' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/mona/venv/softras/lib/python3.8/site-packages/torch/include -I/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/TH -I/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/THC -I/home/mona/venv/softras/include -I/usr/include/python3.8 -c soft_renderer/cuda/load_textures_cuda.cpp -o build/temp.linux-x86_64-3.8/soft_renderer/cuda/load_textures_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=load_textures -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
In file included from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from soft_renderer/cuda/load_textures_cuda.cpp:1:
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:83: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   83 | #pragma omp parallel for if ((end - begin) >= grain_size)
      | 
In file included from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/DeviceType.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/Device.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from soft_renderer/cuda/load_textures_cuda.cpp:1:
soft_renderer/cuda/load_textures_cuda.cpp: In function ‘at::Tensor load_textures(at::Tensor, at::Tensor, at::Tensor, at::Tensor)’:
soft_renderer/cuda/load_textures_cuda.cpp:13:42: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   13 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                          ^
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/macros/Macros.h:173:65: note: in definition of macro ‘C10_UNLIKELY’
  173 | #define C10_UNLIKELY(expr)  (__builtin_expect(static_cast<bool>(expr), 0))
      |                                                                 ^~~~
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:362:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
  362 |   if (C10_UNLIKELY_OR_CONST(!(cond))) {                                 \
      |       ^~~~~~~~~~~~~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:13:23: note: in expansion of macro ‘TORCH_CHECK’
   13 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                       ^~~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:15:24: note: in expansion of macro ‘CHECK_CUDA’
   15 | #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
      |                        ^~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:24:5: note: in expansion of macro ‘CHECK_INPUT’
   24 |     CHECK_INPUT(image);
      |     ^~~~~~~~~~~
In file included from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from soft_renderer/cuda/load_textures_cuda.cpp:1:
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:303:30: note: declared here
  303 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/DeviceType.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/Device.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from soft_renderer/cuda/load_textures_cuda.cpp:1:
soft_renderer/cuda/load_textures_cuda.cpp:13:42: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   13 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                          ^
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/macros/Macros.h:173:65: note: in definition of macro ‘C10_UNLIKELY’
  173 | #define C10_UNLIKELY(expr)  (__builtin_expect(static_cast<bool>(expr), 0))
      |                                                                 ^~~~
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:362:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
  362 |   if (C10_UNLIKELY_OR_CONST(!(cond))) {                                 \
      |       ^~~~~~~~~~~~~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:13:23: note: in expansion of macro ‘TORCH_CHECK’
   13 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                       ^~~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:15:24: note: in expansion of macro ‘CHECK_CUDA’
   15 | #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
      |                        ^~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:25:5: note: in expansion of macro ‘CHECK_INPUT’
   25 |     CHECK_INPUT(faces);
      |     ^~~~~~~~~~~
In file included from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from soft_renderer/cuda/load_textures_cuda.cpp:1:
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:303:30: note: declared here
  303 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/DeviceType.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/Device.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from soft_renderer/cuda/load_textures_cuda.cpp:1:
soft_renderer/cuda/load_textures_cuda.cpp:13:42: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   13 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                          ^
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/macros/Macros.h:173:65: note: in definition of macro ‘C10_UNLIKELY’
  173 | #define C10_UNLIKELY(expr)  (__builtin_expect(static_cast<bool>(expr), 0))
      |                                                                 ^~~~
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:362:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
  362 |   if (C10_UNLIKELY_OR_CONST(!(cond))) {                                 \
      |       ^~~~~~~~~~~~~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:13:23: note: in expansion of macro ‘TORCH_CHECK’
   13 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                       ^~~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:15:24: note: in expansion of macro ‘CHECK_CUDA’
   15 | #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
      |                        ^~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:26:5: note: in expansion of macro ‘CHECK_INPUT’
   26 |     CHECK_INPUT(is_update);
      |     ^~~~~~~~~~~
In file included from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from soft_renderer/cuda/load_textures_cuda.cpp:1:
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:303:30: note: declared here
  303 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/DeviceType.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/Device.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from soft_renderer/cuda/load_textures_cuda.cpp:1:
soft_renderer/cuda/load_textures_cuda.cpp:13:42: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   13 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                          ^
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/macros/Macros.h:173:65: note: in definition of macro ‘C10_UNLIKELY’
  173 | #define C10_UNLIKELY(expr)  (__builtin_expect(static_cast<bool>(expr), 0))
      |                                                                 ^~~~
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:362:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
  362 |   if (C10_UNLIKELY_OR_CONST(!(cond))) {                                 \
      |       ^~~~~~~~~~~~~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:13:23: note: in expansion of macro ‘TORCH_CHECK’
   13 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                       ^~~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:15:24: note: in expansion of macro ‘CHECK_CUDA’
   15 | #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
      |                        ^~~~~~~~~~
soft_renderer/cuda/load_textures_cuda.cpp:27:5: note: in expansion of macro ‘CHECK_INPUT’
   27 |     CHECK_INPUT(textures);
      |     ^~~~~~~~~~~
In file included from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/mona/venv/softras/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from soft_renderer/cuda/load_textures_cuda.cpp:1:
/home/mona/venv/softras/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:303:30: note: declared here
  303 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    setup(
  File "/home/mona/venv/softras/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/mona/venv/softras/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/mona/venv/softras/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/mona/venv/softras/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/mona/venv/softras/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/mona/venv/softras/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.8/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/mona/venv/softras/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/mona/venv/softras/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/mona/venv/softras/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/usr/lib/python3.8/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/mona/venv/softras/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 456, in unix_wrap_single_compile
    cflags = unix_cuda_flags(cflags)
  File "/home/mona/venv/softras/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 423, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/mona/venv/softras/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1561, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
```

```
(softras) mona@goku:~/research/code/SoftRas$ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.8.0+cu111'

$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

```

**Comment by SamMohel** [comment]
excuse me did you solve it ?
