### ISSUE TITLE
request for checkpoint_0200000.pth.tar

### ISSUE THREAD

**Issue by monacv** [ShichenLiu/SoftRas#73]
Hello,

Would you please be able to share this file with me? jalal@bu.edu
data/results/models/recon/checkpoint_0200000.pth.tar

Thanks a lot
Mona

**Comment by monacv** [comment]
When I trained the model, the checkpoint_0200000.pth file wasn't created. I ran it again and it didn't continue and started from the first checkpoint. Could you please guide?
```

(softras) mona@goku:~/research/code$ cd SoftRas/
(softras) mona@goku:~/research/code/SoftRas$ ls
total 56K
drwxrwxr-x 22 mona mona 4.0K Mar 17 00:21 ..
-rw-rw-r--  1 mona mona 5.8K Mar 17 00:21 README.md
-rw-rw-r--  1 mona mona 1.2K Mar 17 00:21 LICENSE
-rw-rw-r--  1 mona mona 1.4K Mar 17 00:21 .gitignore
drwxrwxr-x  4 mona mona 4.0K Mar 17 00:21 soft_renderer
-rw-rw-r--  1 mona mona 1.4K Mar 17 00:21 setup.py
drwxrwxr-x  8 mona mona 4.0K Mar 17 00:21 .git
drwxrwxr-x  3 mona mona 4.0K Mar 17 00:21 examples
drwxrwxr-x  2 mona mona 4.0K Mar 17 12:50 soft_renderer.egg-info
drwxrwxr-x  5 mona mona 4.0K Mar 17 12:51 build
drwxrwxr-x  2 mona mona 4.0K Mar 17 12:51 dist
drwxrwxr-x  9 mona mona 4.0K Mar 17 12:51 .
drwxrwxr-x  6 mona mona 4.0K Mar 17 13:20 data
(softras) mona@goku:~/research/code/SoftRas$ ls data/results/models/recon/checkpoint_0200000.pth.tar
ls: cannot access 'data/results/models/recon/checkpoint_0200000.pth.tar': No such file or directory
(softras) mona@goku:~/research/code/SoftRas$ ls data/results/models/recon/checkpoint_0200000.pth
ls: cannot access 'data/results/models/recon/checkpoint_0200000.pth': No such file or directory
(softras) mona@goku:~/research/code/SoftRas$ ls data/results/models/recon/
total 5.9G
drwxrwxr-x 3 mona mona 4.0K Mar 17 13:48 ..
-rw-rw-r-- 1 mona mona 299M Mar 17 13:50 checkpoint_0000000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 17 13:50 demo_0000000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 13:56 demo_0001000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 14:04 demo_0002000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 14:12 demo_0003000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 14:19 demo_0004000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 14:26 demo_0005000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 14:32 demo_0006000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 14:39 demo_0007000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 14:46 demo_0008000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 14:53 demo_0009000.obj
-rw-rw-r-- 1 mona mona 299M Mar 17 15:00 checkpoint_0010000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 17 15:00 demo_0010000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 15:06 demo_0011000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 15:13 demo_0012000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 15:20 demo_0013000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 15:27 demo_0014000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 15:34 demo_0015000.obj
-rw-rw-r-- 1 mona mona  41K Mar 17 15:41 demo_0016000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 15:47 demo_0017000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 15:54 demo_0018000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 16:01 demo_0019000.obj
-rw-rw-r-- 1 mona mona 299M Mar 17 16:08 checkpoint_0020000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 17 16:08 demo_0020000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 16:15 demo_0021000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 16:22 demo_0022000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 16:29 demo_0023000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 16:36 demo_0024000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 16:43 demo_0025000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 16:50 demo_0026000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 16:57 demo_0027000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 17:04 demo_0028000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 17:11 demo_0029000.obj
-rw-rw-r-- 1 mona mona 299M Mar 17 17:18 checkpoint_0030000.pth.tar
-rw-rw-r-- 1 mona mona  41K Mar 17 17:18 demo_0030000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 17:25 demo_0031000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 17:32 demo_0032000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 17:39 demo_0033000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 17:47 demo_0034000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 17:53 demo_0035000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 18:00 demo_0036000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 18:07 demo_0037000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 18:15 demo_0038000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 18:22 demo_0039000.obj
-rw-rw-r-- 1 mona mona 299M Mar 17 18:29 checkpoint_0040000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 17 18:29 demo_0040000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 18:37 demo_0041000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 18:44 demo_0042000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 18:51 demo_0043000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 18:58 demo_0044000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 19:05 demo_0045000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 19:12 demo_0046000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 19:19 demo_0047000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 19:26 demo_0048000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 19:34 demo_0049000.obj
-rw-rw-r-- 1 mona mona 299M Mar 17 19:43 checkpoint_0050000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 17 19:43 demo_0050000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 19:52 demo_0051000.obj
-rw-rw-r-- 1 mona mona  41K Mar 17 20:02 demo_0052000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 20:10 demo_0053000.obj
-rw-rw-r-- 1 mona mona  41K Mar 17 20:19 demo_0054000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 20:27 demo_0055000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 20:34 demo_0056000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 20:41 demo_0057000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 20:48 demo_0058000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 20:55 demo_0059000.obj
-rw-rw-r-- 1 mona mona 299M Mar 17 21:01 checkpoint_0060000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 17 21:01 demo_0060000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 21:08 demo_0061000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 21:15 demo_0062000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 21:22 demo_0063000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 21:29 demo_0064000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 21:35 demo_0065000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 21:42 demo_0066000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 21:49 demo_0067000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 21:56 demo_0068000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 22:03 demo_0069000.obj
-rw-rw-r-- 1 mona mona 299M Mar 17 22:09 checkpoint_0070000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 17 22:09 demo_0070000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 22:16 demo_0071000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 22:23 demo_0072000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 22:30 demo_0073000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 22:36 demo_0074000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 22:43 demo_0075000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 22:50 demo_0076000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 22:57 demo_0077000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 23:04 demo_0078000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 23:10 demo_0079000.obj
-rw-rw-r-- 1 mona mona 299M Mar 17 23:17 checkpoint_0080000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 17 23:17 demo_0080000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 23:24 demo_0081000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 23:31 demo_0082000.obj
-rw-rw-r-- 1 mona mona  41K Mar 17 23:38 demo_0083000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 23:44 demo_0084000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 23:51 demo_0085000.obj
-rw-rw-r-- 1 mona mona  40K Mar 17 23:58 demo_0086000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 00:05 demo_0087000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 00:12 demo_0088000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 00:18 demo_0089000.obj
-rw-rw-r-- 1 mona mona 299M Mar 18 00:25 checkpoint_0090000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 18 00:25 demo_0090000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 00:32 demo_0091000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 00:39 demo_0092000.obj
-rw-rw-r-- 1 mona mona  41K Mar 18 00:46 demo_0093000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 00:52 demo_0094000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 00:59 demo_0095000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 01:06 demo_0096000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 01:13 demo_0097000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 01:20 demo_0098000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 01:26 demo_0099000.obj
-rw-rw-r-- 1 mona mona 299M Mar 18 01:33 checkpoint_0100000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 18 01:33 demo_0100000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 01:40 demo_0101000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 01:47 demo_0102000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 01:54 demo_0103000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 02:00 demo_0104000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 02:07 demo_0105000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 02:14 demo_0106000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 02:21 demo_0107000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 02:28 demo_0108000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 02:35 demo_0109000.obj
-rw-rw-r-- 1 mona mona 299M Mar 18 02:41 checkpoint_0110000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 18 02:41 demo_0110000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 02:48 demo_0111000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 02:55 demo_0112000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 03:02 demo_0113000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 03:09 demo_0114000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 03:15 demo_0115000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 03:22 demo_0116000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 03:29 demo_0117000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 03:36 demo_0118000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 03:43 demo_0119000.obj
-rw-rw-r-- 1 mona mona 299M Mar 18 03:49 checkpoint_0120000.pth.tar
-rw-rw-r-- 1 mona mona  41K Mar 18 03:49 demo_0120000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 03:56 demo_0121000.obj
-rw-rw-r-- 1 mona mona  41K Mar 18 04:03 demo_0122000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 04:10 demo_0123000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 04:17 demo_0124000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 04:23 demo_0125000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 04:30 demo_0126000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 04:37 demo_0127000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 04:44 demo_0128000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 04:51 demo_0129000.obj
-rw-rw-r-- 1 mona mona 299M Mar 18 04:57 checkpoint_0130000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 18 04:57 demo_0130000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 05:04 demo_0131000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 05:11 demo_0132000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 05:18 demo_0133000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 05:25 demo_0134000.obj
-rw-rw-r-- 1 mona mona  41K Mar 18 05:32 demo_0135000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 05:38 demo_0136000.obj
-rw-rw-r-- 1 mona mona  41K Mar 18 05:45 demo_0137000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 05:52 demo_0138000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 05:59 demo_0139000.obj
-rw-rw-r-- 1 mona mona 299M Mar 18 06:06 checkpoint_0140000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 18 06:06 demo_0140000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 06:12 demo_0141000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 06:19 demo_0142000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 06:26 demo_0143000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 06:33 demo_0144000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 06:40 demo_0145000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 06:46 demo_0146000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 06:53 demo_0147000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 07:00 demo_0148000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 07:07 demo_0149000.obj
-rw-rw-r-- 1 mona mona 299M Mar 18 07:14 checkpoint_0150000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 18 07:14 demo_0150000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 07:20 demo_0151000.obj
-rw-rw-r-- 1 mona mona  41K Mar 18 07:26 demo_0152000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 07:32 demo_0153000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 07:38 demo_0154000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 07:44 demo_0155000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 07:50 demo_0156000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 07:56 demo_0157000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 08:03 demo_0158000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 08:09 demo_0159000.obj
-rw-rw-r-- 1 mona mona 299M Mar 18 08:15 checkpoint_0160000.pth.tar
-rw-rw-r-- 1 mona mona  41K Mar 18 08:15 demo_0160000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 08:21 demo_0161000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 08:27 demo_0162000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 08:33 demo_0163000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 08:39 demo_0164000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 08:46 demo_0165000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 08:52 demo_0166000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 08:58 demo_0167000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 09:04 demo_0168000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 09:10 demo_0169000.obj
-rw-rw-r-- 1 mona mona 299M Mar 18 09:16 checkpoint_0170000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 18 09:16 demo_0170000.obj
-rw-rw-r-- 1 mona mona  41K Mar 18 09:22 demo_0171000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 09:28 demo_0172000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 09:35 demo_0173000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 09:41 demo_0174000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 09:47 demo_0175000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 09:53 demo_0176000.obj
-rw-rw-r-- 1 mona mona  41K Mar 18 09:59 demo_0177000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 10:05 demo_0178000.obj
-rw-rw-r-- 1 mona mona  41K Mar 18 10:12 demo_0179000.obj
-rw-rw-r-- 1 mona mona 299M Mar 18 10:21 checkpoint_0180000.pth.tar
-rw-rw-r-- 1 mona mona  41K Mar 18 10:21 demo_0180000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 10:29 demo_0181000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 10:38 demo_0182000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 10:47 demo_0183000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 10:56 demo_0184000.obj
-rw-rw-r-- 1 mona mona  41K Mar 18 11:05 demo_0185000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 11:14 demo_0186000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 11:20 demo_0187000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 11:26 demo_0188000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 11:32 demo_0189000.obj
-rw-rw-r-- 1 mona mona 299M Mar 18 11:39 checkpoint_0190000.pth.tar
-rw-rw-r-- 1 mona mona  40K Mar 18 11:39 demo_0190000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 11:45 demo_0191000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 11:52 demo_0192000.obj
-rw-rw-r-- 1 mona mona  41K Mar 18 12:00 demo_0193000.obj
-rw-rw-r-- 1 mona mona  40K Mar 18 12:06 demo_0194000.obj
drwxrwxr-x 3 mona mona  12K Mar 18 12:15 .
-rw-rw-r-- 1 mona mona  40K Mar 18 12:15 demo_0195000.obj
drwxrwxr-x 2 mona mona  20K Mar 18 12:15 pic
(softras) mona@goku:~/research/code/SoftRas$ CUDA_VISIBLE_DEVICES=0 python examples/recon/train.py -eid recon
Loading dataset: 100%|██████████████████████████████████████████████████████████████████| 13/13 [00:45<00:00,  3.52s/it]
Iter: [0/250000]	Time 1.102	Loss 0.655	lr 0.000100	sv 0.000100	
```

**Comment by ShichenLiu** [comment]
Hi, you can either change the max iteration to 200001 or simply use 190000 iteration results. They should produce similar results

**Comment by aryachiranjeev** [comment]
How can we run this train.py on google, colab its crashing and showing no results for even 1 iteration.

**Comment by ShichenLiu** [comment]
Hi @aryachiranjeev , I will try to update this repo slightly during this weekend. Hopefully I can provide you a checkpoint then.

**Comment by aryachiranjeev** [comment]
> Hi @aryachiranjeev , I will try to update this repo slightly during this weekend. Hopefully I can provide you a checkpoint then.

Thanks a lot !!

**Comment by ShichenLiu** [comment]
Hi @aryachiranjeev , I just update the repo and upload the checkpoints, feel free to give it a try! But I am afraid you still need to build this repo, as our customized operator is required to convert the mesh to voxels for evaluation. Of course, you can skip this step if you only want the mesh output.

**Comment by aryachiranjeev** [comment]
> Hi @aryachiranjeev , I just update the repo and upload the checkpoints, feel free to give it a try! But I am afraid you still need to build this repo, as our customized operator is required to convert the mesh to voxels for evaluation. Of course, you can skip this step if you only want the mesh output.

Sir where have you uploaded the checkpoints, I am unable to find the checkpoints file. I want to generate mesh from single 2D image. By using test.py file because on colab I can't train the file(train.py). Can you please tell where is the checkpoints file?

**Comment by ShichenLiu** [comment]
Hi @aryachiranjeev ,

Right above this section:

https://github.com/ShichenLiu/SoftRas#2-image-based-shape-deformation

**Comment by aryachiranjeev** [comment]
When I run !CUDA_VISIBLE_DEVICES=0 python3 examples/recon/test.py -eid recon \ 
-d '/content/drive/MyDrive/SoftRas-master/SoftRas-master/SoftRas-master/data/results/models/recon/softras_shading_checkpoint.pth.tar'. Got this error



![Capture](https://user-images.githubusercontent.com/31439731/122556991-cfafbe00-d059-11eb-884d-74266f7c6629.PNG)

Loading dataset: 100% 13/13 [00:06<00:00,  2.00it/s]
tcmalloc: large alloc 1721499648 bytes == 0x55bbebaf0000 @  0x7f98c4b4d1e7 0x7f987093f46e 0x7f987098fc7b 0x7f987098fd18 0x7f9870a37010 0x7f9870a3773c 0x7f9870a3785d 0x55bae69c0f68 0x7f987097cef7 0x55bae69bec47 0x55bae69bea50 0x55bae6a32453 0x55bae6a2d4ae 0x55bae69c03ea 0x55bae6a2f32a 0x55bae6a2d4ae 0x55bae69c0a81 0x55bae6a01d79 0x55bae69fecc4 0x55bae69bf462 0x55bae6a32fd5 0x55bae6a2d4ae 0x55bae6a2d1b3 0x55bae6af7182 0x55bae6af74fd 0x55bae6af73a6 0x55bae6ace723 0x55bae6ace3cc 0x7f98c3937bf7 0x55bae6ace2aa
Traceback (most recent call last):
  File "examples/recon/test.py", line 116, in <module>
    test()
  File "examples/recon/test.py", line 83, in test
    batch_iou, vertices, faces = model(images, voxels=voxels, task='test')
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/SoftRas-master/SoftRas-master/SoftRas-master/examples/recon/models.py", line 148, in forward
    return self.evaluate_iou(images, voxels)
  File "/content/drive/My Drive/SoftRas-master/SoftRas-master/SoftRas-master/examples/recon/models.py", line 139, in evaluate_iou
    voxels_predict = srf.voxelization(faces_norm, 32, False).cpu().numpy()
  File "/usr/local/lib/python3.7/dist-packages/soft_renderer-1.0.0-py3.7-linux-x86_64.egg/soft_renderer/functional/voxelization.py", line 56, in voxelization
    voxels = voxelize_sub3(faces, voxels)
  File "/usr/local/lib/python3.7/dist-packages/soft_renderer-1.0.0-py3.7-linux-x86_64.egg/soft_renderer/functional/voxelization.py", line 29, in voxelize_sub3
    voxels, visible = voxelization_cuda.voxelize_sub3(faces, voxels, visible)
**RuntimeError: voxels must be contiguous**

**Comment by ShichenLiu** [comment]
this is weird, I never met this error. what if you manually make the voxels contiguous?
