### ISSUE TITLE
FAILED: load_textures_cuda_kernel.obj

### ISSUE THREAD

**Issue by mudimingquedeyinmoujia** [ShichenLiu/SoftRas#90]
torch 1.6
cuda 10.1
when I build it doesn't works, and I find that it uses the cuda path "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc" in the error log below, maybe is the reason?
but i don't install cuda 10.0 and you said to use cuda 10.1 in readme.
what should i do ?

> (song) E:\1 codes\SoftRas>python setup.py install
running install
running bdist_egg
running egg_info
writing soft_renderer.egg-info\PKG-INFO
writing dependency_links to soft_renderer.egg-info\dependency_links.txt
writing requirements to soft_renderer.egg-info\requires.txt
writing top-level names to soft_renderer.egg-info\top_level.txt
reading manifest file 'soft_renderer.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'soft_renderer.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
D:\Anaconda3\envs\song\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'soft_renderer.cuda.load_textures' extension
Emitting ninja build file E:\1 codes\SoftRas\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHs
c -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexpo
rt_assumed -ID:\Anaconda3\envs\song\lib\site-packages\torch\include -ID:\Anaconda3\envs\song\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\song\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\song\li
b\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -ID:\Anaconda3\envs\song\include -ID:\Anaconda3\envs\song\include -ID:\VisualStudioFiles\IDE\VC\Tools\MSVC\14.25.28610\include "-IC:
\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-ID:\Windows Kits\10\include\10.0.18362.0\ucrt" "-ID:\Windows Kits\10\include\10.0.18362.0\shared" "-ID:\Windows Kits\10\include\10.0.18362.0\um" "-ID:\Windows Kits\10\include
\10.0.18362.0\winrt" "-ID:\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c "E:\1 codes\SoftRas\soft_renderer\cuda\load_textures_cuda_kernel.cu" -o "E:\1 codes\SoftRas\build\temp.win-amd64-3.7\Release\soft_renderer/cuda/load_textures_
cuda_kernel.obj" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=load_textures -D_GLIBCXX_USE_CXX11_ABI=0 -gencod
e=arch=compute_75,code=sm_75
FAILED: E:/1 codes/SoftRas/build/temp.win-amd64-3.7/Release/soft_renderer/cuda/load_textures_cuda_kernel.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcu
dafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_ass
umed -ID:\Anaconda3\envs\song\lib\site-packages\torch\include -ID:\Anaconda3\envs\song\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\song\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\song\lib\site
-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -ID:\Anaconda3\envs\song\include -ID:\Anaconda3\envs\song\include -ID:\VisualStudioFiles\IDE\VC\Tools\MSVC\14.25.28610\include "-IC:\Progr
am Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-ID:\Windows Kits\10\include\10.0.18362.0\ucrt" "-ID:\Windows Kits\10\include\10.0.18362.0\shared" "-ID:\Windows Kits\10\include\10.0.18362.0\um" "-ID:\Windows Kits\10\include\10.0.
18362.0\winrt" "-ID:\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c "E:\1 codes\SoftRas\soft_renderer\cuda\load_textures_cuda_kernel.cu" -o "E:\1 codes\SoftRas\build\temp.win-amd64-3.7\Release\soft_renderer/cuda/load_textures_cuda_k
ernel.obj" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=load_textures -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch
=compute_75,code=sm_75
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: 句柄无效。

>Traceback (most recent call last):
  File "D:\Anaconda3\envs\song\lib\site-packages\torch\utils\cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "D:\Anaconda3\envs\song\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "D:\Anaconda3\envs\song\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\Anaconda3\envs\song\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Anaconda3\envs\song\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda3\envs\song\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\envs\song\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Anaconda3\envs\song\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Anaconda3\envs\song\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda3\envs\song\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\envs\song\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Anaconda3\envs\song\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "D:\Anaconda3\envs\song\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda3\envs\song\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\envs\song\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Anaconda3\envs\song\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Anaconda3\envs\song\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda3\envs\song\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\envs\song\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\Anaconda3\envs\song\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\Anaconda3\envs\song\lib\site-packages\torch\utils\cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Anaconda3\envs\song\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "D:\Anaconda3\envs\song\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Anaconda3\envs\song\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Anaconda3\envs\song\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "D:\Anaconda3\envs\song\lib\site-packages\torch\utils\cpp_extension.py", line 631, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "D:\Anaconda3\envs\song\lib\site-packages\torch\utils\cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "D:\Anaconda3\envs\song\lib\site-packages\torch\utils\cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by NathanWaaang** [comment]
I met the same issue. Have you fixed it? @mudimingquedeyinmoujia

**Comment by hui1123** [comment]
Me，too。Have you fixed it? @mudimingquedeyinmoujia

**Comment by hui1123** [comment]
Me，too。Have you fixed it? @mudimingquedeyinmoujia

**Comment by NathanWaaang** [comment]
> Me，too。Have you fixed it? @mudimingquedeyinmoujia

I solved my problem by #84 , maybe you can try it

**Comment by hui1123** [comment]
I&nbsp; have solved it recently.&nbsp; Thank you!



---Original---
From: "Nathan ***@***.***&gt;
Date: Tue, Nov 16, 2021 20:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ShichenLiu/SoftRas] FAILED: load_textures_cuda_kernel.obj (#90)




  
Me，too。Have you fixed it? @mudimingquedeyinmoujia
  
I solved my problem by #84 , maybe you can try it
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
