### ISSUE TITLE
 undefined symbol: cudaSetupArgument

### ISSUE THREAD

**Issue by wangleishan** [ShichenLiu/SoftRas#92]
After I finished processing dependencies for soft-renderer==1.0.0， I run you code. But I has a error below. I try python=3.6 or python=3.7. it all failed. my cudatoolkit =10.1.243 .

Traceback (most recent call last):
File "trainval.py", line 8, in
import soft_renderer as sr
File "/home/wangls@1/anaconda3/envs/py37/lib/python3.7/site-packages/soft_renderer-1.0.0-py3.7-linux-x86_64.egg/soft_renderer/init.py", line 1, in
from . import functional
File "/home/wangls@1/anaconda3/envs/py37/lib/python3.7/site-packages/soft_renderer-1.0.0-py3.7-linux-x86_64.egg/soft_renderer/functional/init.py", line 4, in
from .load_obj import load_obj
File "/home/wangls@1/anaconda3/envs/py37/lib/python3.7/site-packages/soft_renderer-1.0.0-py3.7-linux-x86_64.egg/soft_renderer/functional/load_obj.py", line 7, in
import soft_renderer.cuda.load_textures as load_textures_cuda
ImportError: /home/wangls@1/anaconda3/envs/py37/lib/python3.7/site-packages/soft_renderer-1.0.0-py3.7-linux-x86_64.egg/soft_renderer/cuda/load_textures.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

**Comment by ShichenLiu** [comment]
Can you try removing "/home/wangls@1/anaconda3/envs/py37/lib/python3.7/site-packages/soft_renderer-1.0.0-py3.7-linux-x86_64.egg" folder and rebuilding it? It seems that the problem is due to version mismatch between already built modules and current cuda version.

**Comment by wangleishan** [comment]
The error is not resolved, when I create a new environment, the error is still the same .

**Comment by ShichenLiu** [comment]
Can you make sure your system cuda version is also 10.1? Because compiling cuda code does not necessarily use the cudatoolkit version.

**Comment by wangleishan** [comment]
yes. when I use 'nvcc -V'  it show that my cuda version is 10.1

**Comment by cavalier501** [comment]
> yes. when I use 'nvcc -V' it show that my cuda version is 10.1

I also meet the problem, I changed my "nvcc -V" to 10.1 but also have the problem of version dismatch. However, I try again a few days later and the problem is solved
