### ISSUE TITLE
Install Problem: FAILED: C:/.../SoftRas-master/build/temp.win-amd64-3.6/Release/soft_renderer/cuda/soft_rasterize_cuda_kernel.obj

### ISSUE THREAD

**Issue by NathanWaaang** [ShichenLiu/SoftRas#93]
Hi there. When I tried to install SoftRas to my Python env, I came across the following error:
----------------------------------------------------------------------------------------------------
FAILED: C:/.../SoftRas-master/build/temp.win-amd64-3.6/Release/soft_renderer/cuda/soft_rasterize_cuda_kernel.obj
... ...
1 error detected in the compilation of "C:/Users/NATHAN~1/AppData/Local/Temp/tmpxft_00000bec_00000000-8_soft_rasterize_cuda_kernel.cpp4.ii".
soft_rasterize_cuda_kernel.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\Python\Anaconda\envs\DR\lib\site-packages\torch\utils\cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "D:\Python\Anaconda\envs\DR\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:
... ...
  File "D:\Python\Anaconda\envs\DR\lib\site-packages\torch\utils\cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
----------------------------------------------------------------------------------------------------
It seems that soft_rasterize_cuda_kernel.obj cannot be properly loaded, and I tried to double click this file but it cannot be successfully opened.
I tried to install the package on Windows 10, CUDA 10.1, python 3.6
Thank you so much if you could offer any possible help!

**Comment by NathanWaaang** [comment]
I fixed the problem with #84 , it helps a lot!
